version: '3.1'
services:
  mysql-server:
    image: mysql:8
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_USER: appointmentuser61
      MYSQL_PASSWORD: Trabzonspor.61
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: pma
    environment:
      PMA_HOST: mysql-server
      PMA_USER: appointmentuser61
      PMA_PASSWORD: Trabzonspor.61
    ports:
      - "8082:80"
volumes:
  mysql-data: